### ISSUE TITLE
Implement redirect to top-level scheduler page

### ISSUE THREAD

**Issue by benley** [benley/aurora-jobhopper#2]
urls like http://clustername.subdomain don't work, but the README claims they should.

**Comment by SEJeff** [comment]
The fix is really easy for this. Your regex and tests are just wrong.

``` diff
diff --git a/jobhopper/jobhopper.py b/jobhopper/jobhopper.py
index af620ed..f97c12e 100755
--- a/jobhopper/jobhopper.py
+++ b/jobhopper/jobhopper.py
@@ -22,7 +22,7 @@ JOB_RE = r"""
                   (?P<job>         \w[\w.-]*    )\.)?
                (?:(?P<environment> [\w-]+       )\.))?
                   (?P<role>        [\w-]+       )\.
-                  (?P<cluster>     [A-Z]{2}     )
+                  (?P<cluster>     [\w-]+       )
```

The code as is forces the cluster name to only be 2 characters and be uppercase. Additionally, the tests are wrong. Why not use more realistic cluster names like `east-1` in the tests instead of XX? Then it will work.

I can send a PR. It took me about 10 minutes to find this when setting up jobhopper, and then had to pdb to figure out why it wasn't matching anything.

I was invoking jobhopper via:

``` bash
jobhopper.py --port=80 --zk=njb-zkl1:2181,njb-zkl2:2181,njb-zkl1:2181 --zk_basepath=/aurora --scheduler_url=http://njb-zkl1:8081/scheduler --base_domain=<internal_domain> --subdomain=aurora
```

**Comment by benley** [comment]
PR would be totally welcome! I haven't been able to spend time on mesos/aurora/etc projects recently, which has been frustrating.
